# We don't want to start from scratch.
# That is why we tell node here to use the current node image as base.
FROM node:alpine3.11 as build-deps

# Create an application directory
RUN mkdir -p /app

# The /app directory should act as the main application directory
WORKDIR /app

# Copy the app package and package-lock.json file
COPY resume-website/package*.json ./

# Install node packages
RUN npm install

# Copy or project directory (locally) in the current directory of our docker image (/app)
COPY resume-website/ .

# Build the app
RUN npm run build

# Expose PORT on container.
EXPOSE 3000

#production build
FROM nginx:1.16.0-alpine
COPY --from=build-deps /app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY /nginx.conf   /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g","daemon off;"]